name: tree-regularisation
channels:
  - pytorch
  - defaults
dependencies:
  - ipython=7.21.0
  - pillow=8.2.0
  - pydotplus=2.0.2
  - numpy=1.19.2
  - python=3.8.8
  - pandas=1.2.3
  - pytorch=1.8.1
  - scikit-learn=0.24.1
  - matplotlib=3.3.4
  - tensorboard=2.4.0
